export enum AuthActionEnum {
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGOUT = 'LOGOUT',
    AUTH_ERROR = 'AUTH_ERROR',
    REGISTER_SUCCESS = 'REGISTER_SUCCESS',
    REGISTER_ERROR = 'REGISTER_ERROR',
}

export enum ExpenseActionEnum {
    ADD_EXPENSE = 'ADD_EXPENSE',
    UPDATE_EXPENSE = 'UPDATE_EXPENSE',
    DELETE_EXPENSE = 'DELETE_EXPENSE',
    EXPENSE_ERROR = 'EXPENSE_ERROR',
}

