# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available) to /app
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the project files into the docker image
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Start the app using npm start, enabling live reloading
CMD ["npm", "start"]