version: '3.8'
services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile.frontend.dev
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:${BACKEND_PORT}
    restart: on-failure

  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile.backend.dev
    ports:
      - "${BACKEND_PORT}:5000"
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app/backend
      - ./shared:/usr/src/app/shared

    depends_on:
      - database
    environment:
      - DB_URI=${DB_URI}
      - NODE_ENV=development
    restart: on-failure

  database:
    build:
      context: ./
      dockerfile: ./Dockerfile.db.dev
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT}"
    volumes:
      - db-data:/data/db
    restart: on-failure

volumes:
  db-data:
